services:
  # O Banco de Dados PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: csm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: csm_db
    ports:
      - "5433:5432" # Mapeia a porta interna 5432 para 5433 na rede local
    volumes:
      - csm_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d csm_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # O Cache e Mensageria Redis
  redis:
    image: redis:7-alpine
    container_name: csm_redis
    ports:
      - "6379:6379" # Exposta na rede local para a sua máquina principal
    volumes:
      - csm_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  csm_data:
  csm_redis_data: