spring:
  datasource:
    url: jdbc:postgresql://172.19.142.217:5432/csm?currentSchema=csm
    username: admin
    password: senha123

  # Avisamos o Flyway qual o schema principal
  flyway:
    enabled: true
    default-schema: csm
    schemas: csm
    baseline-on-migrate: true

  jpa:
    # Mostra o SQL no console para ajudar no debug
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: csm

    hibernate:
      ddl-auto: none
      naming:
        # Isso faz o Java entender que 'passwordHash' no codigo e 'password_hash' no banco
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
