spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/csm_db?currentSchema=csm
    username: postgres
    password: ${DB_PASSWORD:postgres}

  # Avisamos o Flyway qual o schema principal
  flyway:
    enabled: true
    default-schema: csm
    schemas: csm
    baseline-on-migrate: true

  jpa:
    # Mostra o SQL no console para ajudar no debug
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: csm

    hibernate:
      ddl-auto: none
      naming:
        # Isso faz o Java entender que 'passwordHash' no codigo e 'password_hash' no banco
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    api:
      security:
        token:
          # Nota: A string de fallback precisa ter mais de 32 caracteres para o algoritmo HMAC256 funcionar.
          secret: ${CSM_JWT_SECRET:chave-padrao-provisoria-para-testes-locais-1234567890}